version: '2.2'
services:
  tinberry:
    build: .
    ports:
        - "3478:3478"
        - "3479:3479"
        - "5222:5222"
        - "5223:5223"
        - "5229:5229"
        - "5275:5275"
        - "5276:5276"
        - "5262:5262"
        - "5263:5263"
        - "7070:7070"
        - "7443:7443"
        - "7777:7777"
        - "9090:9090"
        - "9091:9091"
    links:
        - db
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./target/data:/var/lib/mysql
    expose:
        - 3306
